"""Markdown output formatter."""

import re
from scout.types import Report


def _clean(text: str) -> str:
    """Strip HTML tags."""
    return re.sub(r"<[^>]+>", "", text).replace("&#x27;", "'").replace("&amp;", "&")


def format_markdown(report: Report) -> str:
    lines = []
    lines.append(f"# Scout Research Report: {report.topic}")
    lines.append(f"\n*Generated: {report.timestamp} | Depth: {report.config_depth}*\n")

    # Statistics
    stats = report.statistics
    lines.append("## Summary\n")
    lines.append(f"- **Total findings:** {stats.get('total_findings', 0)}")
    lines.append(f"- **Average relevance:** {stats.get('avg_relevance', 0)}")
    sources = stats.get("sources", {})
    for src, count in sources.items():
        lines.append(f"- **{src}:** {count} results")
    lines.append("")

    # Category overview
    lines.append("## Categories\n")
    lines.append("| Category | Count |")
    lines.append("|----------|-------|")
    for c in report.categories:
        lines.append(f"| {c.name} | {c.count} |")
    lines.append("")

    # Top findings by engagement
    top = stats.get("top_engaged", [])
    if top:
        lines.append("## Most Discussed\n")
        for i, t in enumerate(top[:10], 1):
            lines.append(f"{i}. **{_clean(t['title'][:70])}** (score: {t['score']})")
        lines.append("")

    # Category details
    lines.append("## Detailed Findings\n")
    for cat in report.categories:
        lines.append(f"### {cat.name} ({cat.count})\n")
        for f in cat.findings[:8]:
            title = _clean(f.title[:80])
            lines.append(f"- **[{title}]({f.url})**")
            lines.append(f"  - Source: {f.source} | Relevance: {f.relevance_score} | "
                         f"{'↑' + str(f.upvotes) if f.upvotes else '★' + str(f.stars)}")
            if f.snippet:
                snippet = _clean(f.snippet[:200]).replace("\n", " ")
                lines.append(f"  - > {snippet}")
            lines.append("")

    # Pain point sentences
    if report.pain_sentences:
        lines.append("## Extracted Pain Point Statements\n")
        for ps in report.pain_sentences[:20]:
            sent = _clean(ps["sentence"][:200])
            lines.append(f"- {sent}")
            lines.append(f"  *Source: [{_clean(ps['source_title'][:50])}]({ps['source_url']})*")
        lines.append("")

    lines.append("---\n*Generated by [Scout](https://github.com/TROZLAN/scout) — Agentic Web Research powered by Scrapling*")
    return "\n".join(lines)
