"""Plain text output formatter."""

import re
from scout.types import Report


def _clean(text: str) -> str:
    return re.sub(r"<[^>]+>", "", text).replace("&#x27;", "'").replace("&amp;", "&")


def format_text(report: Report) -> str:
    w = 74
    lines = []
    lines.append("=" * w)
    lines.append(f"  SCOUT RESEARCH REPORT: {report.topic.upper()}")
    lines.append(f"  {report.timestamp} | Depth: {report.config_depth}")
    lines.append("=" * w)

    stats = report.statistics
    lines.append(f"\n  Total findings: {stats.get('total_findings', 0)}")
    lines.append(f"  Avg relevance: {stats.get('avg_relevance', 0)}")
    sources = stats.get("sources", {})
    for src, count in sources.items():
        lines.append(f"  {src}: {count} results")

    # Category distribution
    lines.append(f"\n  {'─' * (w - 4)}")
    lines.append("  CATEGORY DISTRIBUTION")
    lines.append(f"  {'─' * (w - 4)}")
    cat_counts = stats.get("categories", {})
    max_count = max(cat_counts.values()) if cat_counts else 1
    for cat, count in cat_counts.items():
        bar_len = int((count / max_count) * 30)
        bar = "#" * bar_len
        lines.append(f"    {cat:<30} {count:>4}  {bar}")

    # Top engaged
    top = stats.get("top_engaged", [])
    if top:
        lines.append(f"\n  {'─' * (w - 4)}")
        lines.append("  MOST DISCUSSED")
        lines.append(f"  {'─' * (w - 4)}")
        for i, t in enumerate(top[:10], 1):
            lines.append(f"  {i:>2}. [{t['score']:>5}] {_clean(t['title'][:60])}")

    # Detailed findings
    lines.append(f"\n  {'─' * (w - 4)}")
    lines.append("  DETAILED FINDINGS")
    lines.append(f"  {'─' * (w - 4)}")
    for cat in report.categories:
        lines.append(f"\n  [{cat.name}] ({cat.count} items)")
        for f in cat.findings[:6]:
            title = _clean(f.title[:65])
            lines.append(f"    - {title}")
            engagement = f"↑{f.upvotes}" if f.upvotes else f"★{f.stars}"
            lines.append(f"      {f.source} | rel:{f.relevance_score} | {engagement} | {f.url[:50]}")
            if f.snippet:
                snippet = _clean(f.snippet[:140]).replace("\n", " ")
                lines.append(f"      > {snippet}")

    # Pain sentences
    if report.pain_sentences:
        lines.append(f"\n  {'─' * (w - 4)}")
        lines.append("  EXTRACTED PAIN POINTS")
        lines.append(f"  {'─' * (w - 4)}")
        for ps in report.pain_sentences[:15]:
            sent = _clean(ps["sentence"][:150])
            lines.append(f"    * {sent}")

    lines.append("\n" + "=" * w)
    lines.append("  Generated by Scout — Agentic Web Research powered by Scrapling")
    lines.append("=" * w)
    return "\n".join(lines)
